"""Make projekt_id nullable on analyse_jobs

Revision ID: ce1b2118ad6b
Revises: ed9e6e477df5
Create Date: 2026-04-16 11:12:55.522654
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ce1b2118ad6b'
down_revision: Union[str, None] = 'ed9e6e477df5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analyse_jobs', 'projekt_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analyse_jobs', 'projekt_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
