"""Add preislisten and produkte tables

Revision ID: ed9e6e477df5
Revises: 001
Create Date: 2026-04-16 10:31:44.065088
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ed9e6e477df5'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preislisten',
    sa.Column('anbieter', sa.String(length=255), nullable=False),
    sa.Column('quelle', sa.String(length=50), nullable=False),
    sa.Column('dateiname', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('produkt_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produkte',
    sa.Column('preisliste_id', sa.UUID(), nullable=False),
    sa.Column('artikel_nr', sa.String(length=100), nullable=True),
    sa.Column('bezeichnung', sa.String(length=500), nullable=False),
    sa.Column('hersteller', sa.String(length=255), nullable=True),
    sa.Column('kategorie', sa.String(length=255), nullable=True),
    sa.Column('einheit', sa.String(length=20), nullable=False),
    sa.Column('preis_netto', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('preis_brutto', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('menge_pro_einheit', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('verfuegbar', sa.Boolean(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['preisliste_id'], ['preislisten.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('analyse_ergebnisse', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('analyse_ergebnisse', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('analyse_jobs', 'projekt_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('analyse_jobs', 'progress',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('analyse_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('analyse_jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('projekte', sa.Column('adresse', sa.String(length=500), nullable=True))
    op.add_column('projekte', sa.Column('plan_nr', sa.String(length=100), nullable=True))
    op.add_column('projekte', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('projekte', sa.Column('architekt', sa.String(length=255), nullable=True))
    op.add_column('projekte', sa.Column('bauherr', sa.String(length=255), nullable=True))
    op.alter_column('projekte', 'beschreibung',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('projekte', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('projekte', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_projekte_auftraggeber'), 'projekte', ['auftraggeber'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projekte_auftraggeber'), table_name='projekte')
    op.alter_column('projekte', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('projekte', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('projekte', 'beschreibung',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=True)
    op.drop_column('projekte', 'bauherr')
    op.drop_column('projekte', 'architekt')
    op.drop_column('projekte', 'status')
    op.drop_column('projekte', 'plan_nr')
    op.drop_column('projekte', 'adresse')
    op.alter_column('analyse_jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('analyse_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('analyse_jobs', 'progress',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('analyse_jobs', 'projekt_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('analyse_ergebnisse', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('analyse_ergebnisse', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_table('produkte')
    op.drop_table('preislisten')
    # ### end Alembic commands ###
