"""add fabrikat fields to position

Revision ID: 074b144a36ad
Revises: e7cbd5ab1474
Create Date: 2026-04-20 07:35:59.793499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '074b144a36ad'
down_revision: Union[str, Sequence[str], None] = 'e7cbd5ab1474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lvp_positions', sa.Column('leit_fabrikat', sa.String(length=200), nullable=False))
    op.add_column('lvp_positions', sa.Column('angebotenes_fabrikat', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lvp_positions', 'angebotenes_fabrikat')
    op.drop_column('lvp_positions', 'leit_fabrikat')
    # ### end Alembic commands ###
