"""initial schema

Revision ID: 6d65f7e5ab0f
Revises: 
Create Date: 2026-04-18 17:56:58.548193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d65f7e5ab0f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('stundensatz_eur', sa.Float(), nullable=False),
    sa.Column('bgk_prozent', sa.Float(), nullable=False),
    sa.Column('agk_prozent', sa.Float(), nullable=False),
    sa.Column('wg_prozent', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.String(length=100), nullable=False),
    sa.Column('target_kind', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_tenant_id'), 'jobs', ['tenant_id'], unique=False)
    op.create_table('lvs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('projekt_name', sa.String(length=300), nullable=False),
    sa.Column('auftraggeber', sa.String(length=300), nullable=False),
    sa.Column('original_dateiname', sa.String(length=500), nullable=False),
    sa.Column('original_pdf_pfad', sa.String(length=500), nullable=False),
    sa.Column('original_pdf_sha256', sa.String(length=64), nullable=False),
    sa.Column('ausgefuelltes_pdf_pfad', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('positionen_gesamt', sa.Integer(), nullable=False),
    sa.Column('positionen_gematcht', sa.Integer(), nullable=False),
    sa.Column('positionen_unsicher', sa.Integer(), nullable=False),
    sa.Column('angebotssumme_netto', sa.Float(), nullable=False),
    sa.Column('price_list_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lvs_tenant_id'), 'lvs', ['tenant_id'], unique=False)
    op.create_table('price_lists',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('haendler', sa.String(length=200), nullable=False),
    sa.Column('niederlassung', sa.String(length=200), nullable=False),
    sa.Column('stand_monat', sa.String(length=20), nullable=False),
    sa.Column('original_dateiname', sa.String(length=500), nullable=False),
    sa.Column('original_pdf_pfad', sa.String(length=500), nullable=False),
    sa.Column('original_pdf_sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('eintraege_gesamt', sa.Integer(), nullable=False),
    sa.Column('eintraege_unsicher', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_lists_tenant_id'), 'price_lists', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('vorname', sa.String(length=100), nullable=False),
    sa.Column('nachname', sa.String(length=100), nullable=False),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lv_id', sa.String(), nullable=False),
    sa.Column('reihenfolge', sa.Integer(), nullable=False),
    sa.Column('oz', sa.String(length=50), nullable=False),
    sa.Column('titel', sa.String(length=300), nullable=False),
    sa.Column('kurztext', sa.Text(), nullable=False),
    sa.Column('langtext', sa.Text(), nullable=False),
    sa.Column('menge', sa.Float(), nullable=False),
    sa.Column('einheit', sa.String(length=20), nullable=False),
    sa.Column('erkanntes_system', sa.String(length=50), nullable=False),
    sa.Column('feuerwiderstand', sa.String(length=20), nullable=False),
    sa.Column('plattentyp', sa.String(length=50), nullable=False),
    sa.Column('materialien', sa.JSON(), nullable=False),
    sa.Column('material_ep', sa.Float(), nullable=False),
    sa.Column('lohn_stunden', sa.Float(), nullable=False),
    sa.Column('lohn_ep', sa.Float(), nullable=False),
    sa.Column('zuschlaege_ep', sa.Float(), nullable=False),
    sa.Column('ep', sa.Float(), nullable=False),
    sa.Column('gp', sa.Float(), nullable=False),
    sa.Column('konfidenz', sa.Float(), nullable=False),
    sa.Column('manuell_korrigiert', sa.Boolean(), nullable=False),
    sa.Column('warnung', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['lv_id'], ['lvs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_lv_id'), 'positions', ['lv_id'], unique=False)
    op.create_table('price_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('price_list_id', sa.String(), nullable=False),
    sa.Column('art_nr', sa.String(length=100), nullable=False),
    sa.Column('dna', sa.String(length=500), nullable=False),
    sa.Column('hersteller', sa.String(length=100), nullable=False),
    sa.Column('kategorie', sa.String(length=100), nullable=False),
    sa.Column('produktname', sa.String(length=300), nullable=False),
    sa.Column('abmessungen', sa.String(length=200), nullable=False),
    sa.Column('variante', sa.String(length=200), nullable=False),
    sa.Column('preis', sa.Float(), nullable=False),
    sa.Column('einheit', sa.String(length=50), nullable=False),
    sa.Column('preis_pro_basis', sa.Float(), nullable=False),
    sa.Column('basis_einheit', sa.String(length=20), nullable=False),
    sa.Column('konfidenz', sa.Float(), nullable=False),
    sa.Column('manuell_korrigiert', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['price_list_id'], ['price_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_entries_dna'), 'price_entries', ['dna'], unique=False)
    op.create_index('ix_price_entries_list_dna', 'price_entries', ['price_list_id', 'dna'], unique=False)
    op.create_index(op.f('ix_price_entries_price_list_id'), 'price_entries', ['price_list_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_entries_price_list_id'), table_name='price_entries')
    op.drop_index('ix_price_entries_list_dna', table_name='price_entries')
    op.drop_index(op.f('ix_price_entries_dna'), table_name='price_entries')
    op.drop_table('price_entries')
    op.drop_index(op.f('ix_positions_lv_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_price_lists_tenant_id'), table_name='price_lists')
    op.drop_table('price_lists')
    op.drop_index(op.f('ix_lvs_tenant_id'), table_name='lvs')
    op.drop_table('lvs')
    op.drop_index(op.f('ix_jobs_tenant_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('tenants')
    # ### end Alembic commands ###
