"""add_pdf_bytes_columns

Revision ID: e7cbd5ab1474
Revises: 380d28ee954d
Create Date: 2026-04-18 20:53:58.131504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7cbd5ab1474'
down_revision: Union[str, Sequence[str], None] = '380d28ee954d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lvp_lvs', sa.Column('original_pdf_bytes', sa.LargeBinary(), nullable=True))
    op.add_column('lvp_lvs', sa.Column('ausgefuelltes_pdf_bytes', sa.LargeBinary(), nullable=True))
    op.add_column('lvp_price_lists', sa.Column('original_pdf_bytes', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lvp_price_lists', 'original_pdf_bytes')
    op.drop_column('lvp_lvs', 'ausgefuelltes_pdf_bytes')
    op.drop_column('lvp_lvs', 'original_pdf_bytes')
    # ### end Alembic commands ###
